server:
  port: 0
logging:
  level:
    root: DEBUG
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Europe/Moscow
        show_sql: false
        type:
          descriptor:
            sql:
              BasicBinder: OFF
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    # Spring Cloud сам подставит реальный порт, если не переопределять руками,
    # но на некоторых сетевых конфигурациях лучше зафиксировать instance-id:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:${random.value}