spring:
  application:
    name: collector
  config:
    import: "config-server:"
    cloud:
      config:
        discovery:
          enabled: true
          serviceId: config-server
  eureka:
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/