server:
  port: 0
logging:
  level:
    root: DEBUG
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopping-store
    username: postgres
    password: postgres
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/